name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Navigate to backend directory
        run: cd restaurante-backend
      - name: Build with Maven
        run: mvn clean install
        working-directory: restaurante-backend
      - name: Run tests
        run: mvn test
        working-directory: restaurante-backend

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Navigate to backend directory
        run: cd restaurante-backend
      - name: Build with Maven
        run: mvn clean package
        working-directory: restaurante-backend
      - name: Deploy to server
        run: |
          # Aqui você adicionaria os comandos para implantar sua aplicação
          # Por exemplo, usando scp para copiar o arquivo JAR para um servidor:
          # scp target/restaurante-backend-1.0-SNAPSHOT.jar user@your-server:/path/to/deploy
          echo "Deployment step - replace with actual deployment commands"
